// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqbmwjhsznbsnsluypvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xYm13amhzem5ic25zbHV5cHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjQ4NTgsImV4cCI6MjA3MjUwMDg1OH0.OR2ezm4viyWn3IMjRzd2rKpv_13dUhdXVZzH1C6Ee5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});